### ISSUE TITLE
Documentation Improvement Request

### ISSUE THREAD

**Issue by rodrigolearns** [Xomics/FAIRDataCube#9]
Dear owners of the FAIRDataCube,

I would like to request an update to the deployment instructions that would allow the latest version of the FAIRDC to be tested locally. I specifically would like a test docker-compose.yml file. Perhaps other updates are also required. For example, there is no bootstrap directory in your repository. If this deployment relies on other repositories to be tested, please indicate so.

Bests,
Rodrigo

**Comment by xiaofengleo** [comment]
Hi Rodrigo, Thank you for your interests and sorry not respond quickly. I need to set the monitoring alert on this repository.
The latest deployment instruction can be found on [FDCube-on-SRC branch](https://github.com/Xomics/FAIRDataCube/tree/FDCube-on-SRC)
Please let me know if you have any questions.
Best,
Xiaofeng
